
const nodemailer = require('nodemailer');

const mailOptions = {
    from: "tokar.emailsender@gmail.com",
    to: "tokar.andrii@ecomm.kiev.ua, alenatokar87@gmail.com",
    subject: "",
    html: "",
};

module.exports = {
    getEmailCredentialsFromFront(req, res, next) {
        console.log(req.body, ' - getEmailCredentialsFromFront req.body')
        const { user, email, subject, message } = req.body;

        const transport = nodemailer.createTransport({
            service: 'gmail',
            host: 'smtp.gmail.com',
            port: 587,
            auth: {
                user: "tokar.emailsender@gmail.com",
                pass: 'T01st456 '
            }
        });

        if (message && email && user && subject) {

            mailOptions.subject = subject;

            mailOptions.html = `
            <h2>Incomming Message from http://localhost:3000/</h2>
            <p>From: <b>${user}</b>, Email: <b>${email}</b></p>
            <br>
            <hr>
            <p>Message: <i>${message}</i></p>
            <br>
            <p><b>Note! Don't reply on this email and send the answer to  - ${email} directly, 
                because this email was generated by http://localhost:3000/ system!!! </b></p>
            `;

            console.log('send mail ...')
            transport.sendMail(mailOptions, (error, info) => {
                if (error) {
                    return console.log(error);
                }
                console.log('Message sent: %s', info.messageId);
            });

            mailOptions.html = "";

            mailOptions.subject = "";

            console.log(mailOptions, ' - mailOptions')
            console.log('skipped mailOptions to empty')

            res.status(200);
            res.send('Ok, message sent succesfully!');
        }

        else {

            console.log('Message Not send!!!! empty send email detail...no message, email, user or subject');
            res.status(406);
            res.send('406 Not Acceptable! Bad Data received...not accepted check the data you input is correct and try again');

        }

        next();

    },


    sendAnswerToFrontOnGet(req, res, next) {
        res.status(200);
        res.send('get method - API works fine!!!');
    }
}